name: bedaya
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.3

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.

dependencies:
  provider: any
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  # provider: ^6.0.0
  intl: any
  url_launcher: ^6.1.9
  flutter_svg: ^2.0.7
  http: ^1.1.0
  shared_preferences: ^2.3.3
  # form field encryption etc
  basic_utils: ^5.4.2
  pointycastle: ^3.6.2
  form_validator: ^2.1.1
  convex_bottom_bar: ^3.1.0+1
  progress_loading_button: ^2.0.2
  photo_card_swiper:
    path: local_packege/photo_card_swiper_main
  animations: ^2.0.7
  expandable: ^5.0.1
  photo_view: ^0.15.0
  file_picker: ^8.1.4
  image_picker: ^1.1.2
  timeago: ^3.7.0
  cached_network_image: ^3.2.3
  badges: ^3.0.2
  like_button: ^2.0.5
  flutter_map: ^7.0.1
  latlong2: ^0.9.0
  confetti: ^0.7.0
  easy_autocomplete: ^1.6.0
  pusher_channels_flutter:
    path: local_packege/pusher_channels_flutter_master
  fbroadcast: ^2.0.0
  emoji_picker_flutter: ^2.1.1
  giphy_get: ^3.2.0
  permission_handler: ^11.0.1
  agora_rtc_engine: ^6.3.2
  flutter_local_notifications:
  android_intent_plus:
  flutter_ringtone_player: ^4.0.0+3
  flutter_smart_dialog: ^4.8.2
  audioplayers: ^6.0.0
  in_app_purchase: ^3.1.7
  in_app_purchase_storekit: ^0.3.6+4
  in_app_purchase_android: ^0.3.0+5
  custom_timer: ^0.2.3
  google_mobile_ads: ^5.1.0
  social_login_buttons: ^1.0.7
  flutter_facebook_auth: 6.0.4
  google_sign_in: ^6.1.4
  responsive_sizer: ^3.3.1
  flutter_localizations:
    sdk: flutter

dependency_overrides: null
# added to fix the issue on ios - 28JUN2023
#webview_flutter_wkwebview: ^3.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

  # For information on the generic Dart part of this file, see the
  # following page: https://dart.dev/tools/pub/pubspec
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.2.16
  flutter_launcher_icons: ^0.13.1

# The following section is specific to Flutter packages.
flutter:
  generate: true

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/logo.png
    - assets/images/logo.svg
    - assets/images/premium-badge.svg
    - assets/images/gift.svg
    - assets/images/bgs/bg.jpg
    - assets/images/bgs/bg1.jpg
    - assets/images/bgs/bg2.jpg
    - assets/audio/caller-ringtone.mp3
    - assets/audio/receiver-ringtone.mp3
    - assets/audio/celebration.mp3

    # An image asset can refer to one or more resolution-specific "variants", see
    # https://flutter.dev/assets-and-images/#resolution-aware
    # For details regarding adding assets from package dependencies, see
    # https://flutter.dev/assets-and-images/#from-packages
    # To add custom fonts to your application, add a fonts section here,
    # in this "flutter" section. Each entry in this list should have a
    # "family" key with the font family name, and a "fonts" key with a
    # list giving the asset and other descriptors for the font. For
    # example:
  fonts:
    - family: Fuzzy_Bubbles
      fonts:
        - asset: assets/fonts/Fuzzy_Bubbles/FuzzyBubbles-Regular.ttf
        - asset: assets/fonts/Fuzzy_Bubbles/FuzzyBubbles-Bold.ttf
          style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
# added
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  #  min_sdk_android: 21 # android min sdk min:16, default 21
  # Icons with alpha channel are not allowed in the Apple App Store.
  remove_alpha_ios: true

flutter_native_splash:
  color: "#000000" # اللون الأزرق للوضع العادي
  image: assets/images/icon.png
  color_dark: "#000000" # اللون الأسود للوضع الداكن
  image_dark: assets/images/icon.png
  android_12:
    color: "#000000"
    image: assets/images/icon.png
    color_dark: "#000000"
    image_dark: assets/images/icon.png

flutter_intl:
  enabled: true
