name: Flutter Build and Release

on:
  push:
    branches:
      - master # تأكد من أن الفرع الذي تريد العمل عليه هو master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3' # حدد إصدار Flutter المطلوب

      - name: Install dependencies
        run: flutter pub get

      # إنشاء نسخة Debug
      - name: Run Flutter build (Debug APK)
        run: flutter build apk --debug

      # إنشاء نسخة Release
      - name: Run Flutter build (Release APK)
        run: flutter build apk --release

      # إنشاء إصدار (Release) في GitHub
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          release_name: "Release v1.0.${{ github.run_number }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

      # رفع نسخة Debug إلى GitHub Release
      - name: Upload Debug APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-debug.apk
          asset_name: app-debug.apk
          asset_content_type: application/vnd.android.package-archive

      # رفع نسخة Release إلى GitHub Release
      - name: Upload Release APK to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive
